WSR_NPI-master/WSR_NPI/Controllers/DeliveryManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using WSR_NPI.DataBase;
using Newtonsoft.Json;
using WSR_NPI.Models;
using WSR_NPI.DataBase.Models;
using WSR_NPI.Crypt;

namespace WSR_NPI.Controllers
{
    [Authorize(Roles = "Менеджер по доставке")]
    public class DeliveryManagerController : Controller
    {
        private Context Context = new Context();
        BaseMethods bM = new BaseMethods();

        // GET: DeliveryManager
        public ActionResult Index()
        {
            var model = Context.Orders.Include(o => o.User).Where(x => x.Status.Equals("Комплектация завершена"));

            return View(model);
        }

        /// <summary>
        /// Содержимое заказа
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var order = Context.Orders.Include(o => o.OrderNoms).Include(o => o.OrderNoms.Select(x => x.Nomenclature)).FirstOrDefault(o => o.Id == id);

            if (order != null)
            {
                return PartialView("Details", order);
            }

            return View("Index");
        }

        /// <summary>
        /// Список курьеров
        /// </summary>
        /// <returns></returns>
        public ActionResult Couriers()
        {
            var model = Context.Сouriers.Include(x => x.User);
            return View(model);
        }

        /// <summary>
        /// Назначение курьера на заказ
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AssignCourierOrder(int id)
        {
            var model = new WSR_NPI.DataBase.Models.Сourier
            {
                OrderId = id
            };

            return PartialView("AssignCourierOrder", model);
        }

        /// <summary>
        /// Назначение курьера на заказ
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AssignCourierOrder(WSR_NPI.DataBase.Models.Сourier model)
        {
            if (ModelState.IsValid)
            {
                var c = Context.Сouriers.Single(x => x.Id == model.Id);
                c.Status = "Доставляет";
                c.OrderId = model.OrderId;

                var order = Context.Orders.Single(x => x.Id == model.OrderId);
                order.Status = "Ожидает курьера";
                var user = Context.Users.Single(x => x.Login.Equals(User.Identity.Name));

                if (SmartCourier(order, c)) 
                {
                    BlockChainManager.GenerateNextBlock(bM.Encrypt(JsonConvert.SerializeObject(order)), user.Id);
                }
                Context.SaveChanges();

                return RedirectToAction("Index");
            }

            return PartialView("AssignCourierOrder", model);
        }

        /// <summary>
        /// Смарт контракт для назначения курьера на заказ
        /// </summary>
        /// <param name="order"></param>
        /// <returns></returns>
        private bool SmartCourier(Order order, WSR_NPI.DataBase.Models.Сourier model)
        {
            var o = Context.Orders.FirstOrDefault(x => x.Id == order.Id);
            var c = Context.Сouriers.Single(x => x.Id == model.Id);

            if (o != null && o.Status.Equals("Ожидает курьера") && c.Status.Equals("Доставляет"))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

WSR_NPI-master/WSR_NPI/Controllers/SalesManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using WSR_NPI.DataBase;
using WSR_NPI.Models;
using WSR_NPI.DataBase.Models;
using Newtonsoft.Json;
using WSR_NPI.Crypt;
using Microsoft.Scripting.Hosting;
using IronPython.Hosting;

namespace WSR_NPI.Controllers
{
    [Authorize(Roles = "Менеджер по продажам")]
    public class SalesManagerController : Controller
    {
        private Context Context = new Context();
        BaseMethods bM = new BaseMethods();
        // GET: SalesManager
        public ActionResult Index()
        {
            return View(Context.Orders.Include(o => o.User));
            
        }

        /// <summary>
        /// Добавление заказа
        /// </summary>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        public ActionResult CreateOrder()
        {
            var model = new CreateOrderViewModel();
            var orderNums = new List<CreateOrderNum>();

            foreach (var nomenclature in Context.Nomenclatures)
            {
                orderNums.Add(new CreateOrderNum
                {
                    Name = nomenclature.Name,
                    Count = nomenclature.Count,
                    IsBuy = false
                });
            }

            model.OrderNums = orderNums;
            return View(model);
        }

        /// <summary>
        /// Добавление заказа
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public ActionResult CreateOrder(CreateOrderViewModel model)
        {
            if (ModelState.IsValid)
            {

                var errorOrderNums = model.OrderNums.Where(o => (o.CountBuy > o.Count) || o.CountBuy < 0 || (o.IsBuy && o.CountBuy == 0));

                if (errorOrderNums.Any())
                {
                    ModelState.AddModelError("", "Проверьте список заказа, вы указали недопустимое число товара");

                    return View(model);
                };

                if (model.OrderNums.Where(x => x.IsBuy).Count() == 0) 
                {
                    ModelState.AddModelError("", "Выберите товар");

                    return View(model);
                }

                var user = Context.Users.Single(u => u.Login.Equals(User.Identity.Name));

                var order = Context.Orders.Add(new Order
                {
                    Adres = model.Adress,
                    UserId = user.Id,
                    Status = "Принят"
                });


                if (SmartCreate(order))
                {
                    var orderData = bM.Encrypt(JsonConvert.SerializeObject(order));
                    ScriptEngine engine = Python.CreateEngine();
                    ScriptScope scope = engine.CreateScope();
                    scope.SetVariable("msg", orderData);
                    engine.ExecuteFile(Server.MapPath("~/Py/keys.py"), scope);
                    dynamic sign = scope.GetVariable("sign");
                    dynamic pubKey = scope.GetVariable("pubKey");

                    BlockChainManager.Path = Server.MapPath("~/Py/varify.py");
                    BlockChainManager.Sign = sign;
                    BlockChainManager.PubKey = pubKey;
                    BlockChainManager.Need = true;
                    BlockChainManager.GenerateNextBlock(orderData, user.Id);
                }

                foreach (var orderNumModel in model.OrderNums.Where(o => o.IsBuy && o.CountBuy > 0))
                {
                    var nomenclature = Context.Nomenclatures.Single(n => n.Name.Equals(orderNumModel.Name));


                    Context.OrderNoms.Add(new OrderNom
                    {
                        OrderId = order.Id,
                        NomenclatureId = nomenclature.Id,
                        CountInOrder = orderNumModel.CountBuy
                    });

                    nomenclature.Count -= orderNumModel.CountBuy;
                    Context.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }



        /// <summary>
        /// Содержимое заказа
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// 
        public ActionResult Details(int id)
        {
            var order = Context.Orders.Include(o => o.OrderNoms).Include(o => o.OrderNoms.Select(x => x.Nomenclature)).FirstOrDefault(o => o.Id == id);

            if (order != null)
            {
                return PartialView("Details", order);
            }

            return View("Index");
        }


        /// <summary>
        /// Редактирование заказа
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var model = new CreateOrderViewModel();
            var orderNums = new List<CreateOrderNum>();

            foreach (var nomenclature in Context.Nomenclatures)
            {
                orderNums.Add(new CreateOrderNum
                {
                    Name = nomenclature.Name,
                    Count = nomenclature.Count,
                    IsBuy = false
                });
            }

            var order = Context.Orders
                .Include(x => x.OrderNoms)
                .Include(x => x.OrderNoms.Select(y => y.Nomenclature))
                .Single(x => x.Id == id);

            foreach (var orderNom in order.OrderNoms)
            {

                var orderNomResult = orderNums.Single(x => x.Name.Equals(orderNom.Nomenclature.Name));

                orderNomResult.IsBuy = true;
                orderNomResult.CountBuy = orderNom.CountInOrder;
                orderNomResult.Count += orderNom.CountInOrder;
            }

            model.OrderNums = orderNums;
            model.Adress = order.Adres;

            return View(model);
        }

        /// <summary>
        /// Редактирование заказа
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(int id, CreateOrderViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var errorOrderNums = model.OrderNums.Where(o => (o.CountBuy > o.Count) || o.CountBuy < 0 || (o.IsBuy && o.CountBuy == 0));

                    if (errorOrderNums.Any())
                    {
                        ModelState.AddModelError("", "Проверьте список заказа, вы указали недопустимое число товара");

                        return View(model);
                    };

                    var order = Context.Orders
                        .Include(x => x.OrderNoms)
                        .Include(x => x.OrderNoms.Select(y => y.Nomenclature))
                        .Single(x => x.Id == id);

                    foreach (var orderNumModel in model.OrderNums)
                    {
                        var orderNom = order.OrderNoms.FirstOrDefault(x => x.Nomenclature.Name.Equals(orderNumModel.Name));
                        var nomenclature = Context.Nomenclatures.Single(n => n.Name.Equals(orderNumModel.Name));

                        if (orderNom != null)
                        {
                            if (orderNumModel.IsBuy)
                            {
                                nomenclature.Count += orderNom.CountInOrder;
                                orderNom.CountInOrder = orderNumModel.CountBuy;
                                nomenclature.Count -= orderNom.CountInOrder;
                            }
                            else
                            {
                                nomenclature.Count += orderNom.CountInOrder;
                                Context.OrderNoms.Remove(orderNom);
                            }

                            Context.SaveChanges();
                        }
                        else
                        {
                            if (orderNumModel.IsBuy)
                            {
                                Context.OrderNoms.Add(new OrderNom
                                {
                                    OrderId = order.Id,
                                    NomenclatureId = nomenclature.Id,
                                    CountInOrder = orderNumModel.CountBuy
                                });

                                nomenclature.Count -= orderNumModel.CountBuy;
                                Context.SaveChanges();
                            }
                        }
                    }


                    return RedirectToAction("Index");
                }

                return View(model);
            }
            catch
            {
                ModelState.AddModelError("", "Ошибка");
                return View(model);
            }
        }

        /// <summary>
        /// Отмена заказа
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Cancel(int id)
        {
            try
            {
                var order = Context.Orders
                           .Include(x => x.OrderNoms)
                           .Include(x => x.OrderNoms.Select(y => y.Nomenclature))
                           .Single(x => x.Id == id);

                foreach (var orderNom in order.OrderNoms)
                {
                    var nomenclature = Context.Nomenclatures.Single(n => n.Id == orderNom.Nomenclature.Id);
                    nomenclature.Count += orderNom.CountInOrder;

                    Context.SaveChanges();
                }

                order.Status = "Отменен";
                var user = Context.Users.Single(x => x.Login.Equals(User.Identity.Name));

WSR_NPI-master/WSR_NPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">WSR</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item text-white">
                        @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>

                    @if (User.IsInRole("Менеджер по продажам"))
                    {
                        <li class="nav-item text-white">
                            @Html.ActionLink("Список заказов", "Index", "SalesManager", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item text-white">
                            @Html.ActionLink("Создать заказ", "CreateOrder", "SalesManager", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }

                    @if (User.IsInRole("Работник склада"))
                    {
                        <li class="nav-item text-white">
                            @Html.ActionLink("Список заказов", "Index", "WarehouseWorker", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }

                    @if (User.IsInRole("Менеджер по доставке"))
                    {
                        <li class="nav-item text-white">
                            @Html.ActionLink("Список заказов", "Index", "DeliveryManager", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item text-white">
                            @Html.ActionLink("Список курьеров", "Couriers", "DeliveryManager", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    <li class="nav-item text-white">
                        @Html.ActionLink("QR коды", "Index", "QRCOde", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>


                @Html.ActionLink("Выход", "Logoff", "Account", new { area = "" }, new { @class = "btn btn-outline-info" })
            </div>
        </nav>
    </div>

    <div class="container body-content" style="padding-top: 25px; padding-bottom: 25px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WSR_NPI</p>
        </footer>
    </div>
</body>
</html>